version: '3.8'
name: datingapp

services:
  # ASP.NET Core Application
  web:
    image: datingapp:latest
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=datingdb;Port=5432;Database=DatingApp;User Id=postgres;Password=admin;Include Error Detail=true
      - TokenKey=jdhsfuhahgtadfgjhazfjklgnjfkdgnksndfklgnkjsdfsgsdfgdjshnfukalhdnfkjlahdngjklkladjf
      - CloudinarySettings__CloudName=dpmjibfhc
      - CloudinarySettings__ApiKey=755843889732679
      - CloudinarySettings__ApiSecret=FIUsXeQdMK80Q7rRHEy1bR_35BE
    depends_on:
      - datingdb

  # PostgreSQL Database
  datingdb:
    container_name: datingdb
    image: postgres
    environment:
      - POSTGRES_DB=DatingApp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: always
    ports:
      - 5431:5432
    volumes:
      - postgres-datingdb:/var/lib/postgresql/data

# Volumes for persistent PostgreSQL data
volumes:
  postgres-datingdb:
